version: '3.3'
services:
  k6:
    image: grafana/k6@sha256:278d78f2953041b6b4b0bd315e8605ed43222245771adc405f3252f3edea0eef
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - VARS=environments/${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
      - API_SUBSCRIPTION_KEY=${sub_key}
      - APICONFIG_SUBSCRIPTION_KEY=${apiconfig_sub_key}
      - GPD_SUBSCRIPTION_KEY=${gpd_sub_key}
      - GPS_SUBSCRIPTION_KEY=${gps_sub_key}
      - DONATIONS_SUBSCRIPTION_KEY=${donations_sub_key}
      - SOAP_SUBSCRIPTION_KEY=${soap_sub_key}
      - DEBT_POSITION_NUMBER=${debt_position_number}
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx@sha256:0f04e4f646a3f14bf31d8bc8d885b6c951fdcf42589d06845f64d18aec6a3c4d
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

