version: '3.3'
services:
  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - VARS=environments/${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
      - API_SUBSCRIPTION_KEY=${sub_key}
      - APICONFIG_SUBSCRIPTION_KEY=${apiconfig_sub_key}
      - GPD_SUBSCRIPTION_KEY=${gpd_sub_key}
      - GPS_SUBSCRIPTION_KEY=${gps_sub_key}
      - DONATIONS_SUBSCRIPTION_KEY=${donations_sub_key}
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "8086:8086"
      - "80:80"

