# azure-pipelines.yml
trigger: none

variables:
  ${{ if eq(parameters['ENVIRONMENT'], 'dev') }}:
    poolImage: 'pagopa-dev-loadtest-linux'
    apiConfigSubscriptionKey: '$(DEV_API_CONFIG_SUBSCRIPTION_KEY)'
    gpdSubscriptionKey: '$(DEV_GPD_SUBSCRIPTION_KEY)'
    gpsSubscriptionKey: '$(DEV_GPS_SUBSCRIPTION_KEY)'
    donationsSubscriptionKey: '$(DEV_DONATIONS_SUBSCRIPTION_KEY)'
  ${{ if eq(parameters['ENVIRONMENT'], 'uat') }}:
    poolImage: 'pagopa-uat-loadtest-linux'
    apiConfigSubscriptionKey: '$(UAT_API_CONFIG_SUBSCRIPTION_KEY)'
    gpdSubscriptionKey: '$(UAT_GPD_SUBSCRIPTION_KEY)'
    gpsSubscriptionKey: '$(UAT_GPS_SUBSCRIPTION_KEY)'
    donationsSubscriptionKey: '$(UAT_DONATIONS_SUBSCRIPTION_KEY)'

pool:
  name: $(poolImage)

parameters:
  - name: "ENVIRONMENT"
    displayName: "Environment"
    type: string
    values:
      - "dev"
      - "uat"
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "load"
      - "spike"
      - "stress"
      - "smoke"
  - name: "DEBT_POSITION_NUMBER"
    displayName: "Debt Positions to preload"
    type: number
    default: 10
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - payments_demand_notice
      - payments_workflow
      - payments_workflow.oneshot
      - verify_payment_workflow
      - get_payment_workflow
      - send_rt_workflow

steps:
  - script: |
      cd ./performance-test/src
      docker pull grafana/k6
    displayName: Pull k6 image
  - script: |
      cd ./performance-test
      sh ./run_performance_test.sh ${{ parameters.ENVIRONMENT }} ${{ parameters.TEST_TYPE }} ${{ parameters.SCRIPT }} gpdpaymentsk6 $(apiConfigSubscriptionKey) $(gpdSubscriptionKey) $(gpsSubscriptionKey) $(donationsSubscriptionKey) ${{ parameters.DEBT_POSITION_NUMBER }}
    displayName: Run k6 ${{ parameters.SCRIPT }} on ${{ parameters.ENVIRONMENT }}