version: '3.8'

services:
  app:
    container_name: 'pagopagpdpayments'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      app_net:
        ipv4_address: 10.20.0.2

  azure-storage:
    container_name: 'azure-storage'
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    networks:
      app_net:
        ipv4_address: 10.20.0.3

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1
