microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-gpd-payments
    tag: "0.11.2"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.gps.internal.dev.platform.pagopa.it"
    path: /pagopa-gpd-payments/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopa-d-gpd-payments-service'
    PAA_ID_INTERMEDIARIO: "15376371009"
    PAA_STAZIONE_INT: "15376371009_01"
    RETRY_MAX_DELAY: "2000"
    RETRY_MAX_ATTEMPTS: "1"
    CONNECTION_TIMEOUT: "3000"
    LOGGING_LEVEL: "INFO"
    CACHE_SIZE: "1000"
    CACHE_EXPIRATION_TIME: "1s"
    AZURE_TABLES_TABLENAME: "gpdpaymentsreceiptstable"
    API_CONFIG_HOST: "https://api.dev.platform.pagopa.it/apiconfig/auth/api/v1"
    GPS_HOST: "https://api.dev.platform.pagopa.it/gps/spontaneous-payments-service/v1"
    GPD_HOST: "https://api.dev.platform.pagopa.it/gpd/api/v1"
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    APICONFIG_SUBSCRIPTION_KEY: "gpd-d-apiconfig-subscription-key"
    GPD_SUBSCRIPTION_KEY: "gpd-d-gpd-subscription-key"
    GPS_SUBSCRIPTION_KEY: "gpd-d-gps-subscription-key"
    AZURE_TABLES_CONNECTION_STRING: "gpd-payments-d-cosmos-connection-string"
  keyvault:
    name: "pagopa-d-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-gpd-payments
        tag: "0.8.0-1-PAGOPA-1140-sviluppo-gpd-payments-gestione-enti-pluri-intermediati"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
