microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopagpdpayments
    tag: "0.0.17"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /info
      port: 8080
    failureThreshold: 60
    periodSeconds: 30
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080
  ingress:
    create: true
    host: "weudev.gps.internal.dev.platform.pagopa.it"
    path: /pagopa-gpd-payments/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopa-d-gpd-payments-service'
    PAA_ID_INTERMEDIARIO: "15376371009"
    PAA_STAZIONE_INT: "15376371009_01"
    RETRY_MAX_DELAY: "2000"
    RETRY_MAX_ATTEMPTS: "1"
    CONNECTION_TIMEOUT: "3000"
    LOGGING_LEVEL: "INFO"
    CACHE_SIZE: "1000"
    CACHE_EXPIRATION_TIME: "1s"
    RECEIPTS_TABLE: "pagopadweugpspaymentssareceiptstable"
    API_CONFIG_HOST: "https://api.dev.platform.pagopa.it/apiconfig/auth/api/v1"
    GPS_HOST: "https://api.dev.platform.pagopa.it/gps/spontaneous-payments-service/v1"
    GPD_HOST: "https://api.dev.platform.pagopa.it/gpd/api/v1"
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    PAYMENTS_SA_CONNECTION_STRING: "gpd-payments-d-sa-connection-string"
    APICONFIG_SUBSCRIPTION_KEY: "gpd-d-apiconfig-subscription-key"
    GPD_SUBSCRIPTION_KEY: "gpd-d-gpd-subscription-key"
    GPS_SUBSCRIPTION_KEY: "gpd-d-gps-subscription-key"
  keyvault:
    name: "pagopa-d-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
